---
- name: Deploy Calculator Container
  hosts: all
    # Ensures Ansible can use Docker (run as root)
  vars:
    image_name: "nivedithavarma/calculator:latest"
    container_name: "Calculator"

  tasks:
    - name: Ensure Python Docker SDK is installed
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Pull latest Calculator image
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Ensure Calculator container is running (idempotent)
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: unless-stopped
        recreate: true        # Replaces container if image changed
        detach: true
